codestates-seb/seb40_main_025

- client/tsconfig.json
- close #31
기존에 ./폴더명으로 import 하던 것을 바로 폴더명을 적는 것으로 수정하였습니다
> 🔨CHORE: 절대 경로 지정

- client/.gitmessage.txt
- client/public/index.html
- client/src/App.tsx
- client/src/index.tsx
- client/src/shared/styled/GlobalStyle.tsx
- client/src/shared/styled/GlobalStyled.js
- client/src/shared/styled/Theme.ts
- client/src/shared/styled/styled.d.ts
theme provider는 기존 jsx에서 쓰듯이 props를 내려서 쓰면 됩니다.
> Theme provider, Global Style 적용

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/controller/CommentController.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/mapper/CommentMapper.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
> [BE] CommentService CRUD, Mapper 미완성

- client/package-lock.json
- client/package.json
🔨CHORE: polished 패키지 설치, 라우팅용 Pagaes 폴더 추가
> 🔨CHORE: polished 패키지 설치, 라우팅용 Pagaes 폴더 추가

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberController.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/mapper/MemberMapper.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/service/MemberService.java
- Member controller 로직 구현, Mapper 추가했습니다
- Oauth2.0 으로 바뀌면 많이 바뀔 예정이어서 구색만 맞춰놨습니다.
- memberService에 findmember 메서드가 구현되었습니다.
> [BE] Member controller 로직 구현, Mapper 추가

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/controller/GalleryController.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/entity/Gallery.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/mapper/GalleryMapper.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/auditable/Auditable.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
- server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/artwork/repository/ArtworkRepositoryTest.java
- server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryServiceMockTest.java
- postGallery 부분만 구현했습니다.
- 다른 도메인의 메서드를 사용해야하는데 할 수 없어서 테스트 코드 등을 작성하지 못했습니다.
- Auditable에서 필드 명을 Date -> At 변경했습니다.
- service에서 findGallery를 구현했습니다.
> [BE] postGallery 구현

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkController.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/gallery/service/GalleryService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/exception/exception/ExceptionCode.java
1. 작품의 갤러리id가 요청받은 갤러리 id일치하는지 검증하는 로직 수정
2. 작품 수정 비지니스 로직 구현
3. 작품 controller와 service 매핑
4. ArtworkService - void verifyArtworkId 메서드(작품 아이디 검증) 삭제
> [Feat] 작품 수정 비지니스 로직 구현

- client/src/GallerySetting/GallerySetting.tsx
- 저장 시 form 데이터 출력으로 변경
- useGalleryData 확인 가능
closed: #109
> ✨Fix : 전시관 관리 - 미적용 해결

- client/src/UploadPicture/index.tsx
- client/src/UploadPicture/types.ts
- client/src/shared/components/Header/components/HeaderButtons.tsx
- client/src/shared/components/Header/hook/useReceiveAlarm.tsx
- client/src/shared/components/Modal/components/ModalBackdrop.tsx
- client/src/shared/components/Modal/components/ModalContainer.ts
- client/src/shared/components/Modal/components/Profile.tsx
- client/src/shared/components/Modal/hook/useClipboardCopy.tsx
- client/src/shared/components/Toast/components/ToastContainer.tsx
- 갤러리 주소 복사
- post시 store에 저장된 갤러리아이디로 요청
> Fe 111 gallarylink

- client/src/GallerySetting/GallerySetting.tsx
- client/src/Intro/RedirectPage.tsx
- client/src/Intro/hooks/tokenStorage.ts
- client/src/Intro/hooks/useUserData.ts
- client/src/SinglePicture/SinglePicture.tsx
- client/src/UploadPicture/api.ts
- client/src/shared/utils/axios.ts
- client/src/store/store.ts
- client/src/store/types.ts
- client/src/types.d.ts
> 🚑FIX:  토큰 저장 오류 해결, 로그인유지 추가

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/repository/AlarmRepository.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
1. 알림 읽음처리 service에 오류가 있어서 수정하였습니다.
2. 테이블 명과 jpql 쿼리명에 대소문자를 일치시켜보았습니다.
> [Fix/#129] 알림 에러수정

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/controller/AlarmController.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/repository/AlarmRepository.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
1. JPQL read update 메소드 삭제, 
2. 알림 로직 수정 (Client는 read false 인 상태로 받고,  확인되면 true로 바뀜)
> [Fix/#129] 알림 로직 및 에러 수정

- client/src/AlarmList/components/Alarm.tsx
- client/src/AlarmList/components/AlarmContainer.ts
- client/src/AlarmList/components/Filter.tsx
- client/src/AlarmList/hooks/useHandleIntersection.tsx
- client/src/AlarmList/types.ts
- client/src/Intro/api.ts
- client/src/shared/components/Header/hook/useReceiveAlarm.tsx
- client/src/shared/components/Modal/AlertData.ts
- client/src/shared/components/Modal/Profile.tsx
- client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
- client/src/shared/components/Modal/hooks/useHandleService.tsx
- client/src/shared/hooks/useNavigateSearch.tsx
-  알림 필터수정
- 로그아웃, 회원탈퇴시 localstorage 초기화 추가
-  useNavigateSearch 사용시 모달창 전체 끄기
- 버튼 커서 포인터 수정
- 알람 클릭시 SingleFic으로 이동
> [FE] 자잘한 기능 수정

- client/src/App.tsx
- client/src/Gallery/GalleryAllPic.tsx
- client/src/Gallery/GalleryFourPic.tsx
- client/src/Gallery/components/BottonButton/index.tsx
- client/src/Gallery/components/BottonButton/style.tsx
- client/src/Gallery/components/DynamicGallery/index.tsx
- client/src/Gallery/components/FourCut/index.tsx
- client/src/Gallery/components/FourCut/style.tsx
- client/src/GallerySetting/components/Input/index.tsx
- client/src/GallerySetting/components/Input/style.tsx
- client/src/index.tsx
> [FE] 전시관 관리 페이지 - 에러 해결, 라우팅

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/dto/AlarmResponseDto.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
1. 알림 Id 를 클라이언트에서 확인 할 수 있게 수정해두었습니다.
2. 빈 댓글이나 답글을 받을시 204 No Content 로 확인할 수 있게 수정해두었습니다.
> [BE/#144] 알림 ID 및 빈 페이지 No content 

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/AlarmType.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
1. 프론트분들 요청으로 대댓글 또한 Artwork, Gallery인지 구분을 두었습니다.
> [Feat] 대댓글 알림 response 카테고리 추가

- client/src/shared/components/Header/components/HeaderBox.tsx
- client/src/shared/components/Header/hook/useReceiveAlarm.tsx
- client/src/shared/components/Header/index.tsx
- client/src/shared/utils/axios.ts
> Fe inspection

- client/src/AlarmList/index.tsx
- client/src/ForBidden/index.tsx
- client/src/UploadPicture/index.tsx
- client/src/shared/components/Header/hook/useReceiveAlarm.tsx
- client/src/shared/components/Header/index.tsx
- client/src/shared/components/Modal/components/ModalContainer.ts
- client/src/shared/components/Toast/ToastData.tsx
- client/src/shared/styled/GlobalStyle.tsx
- 업로드시 내 전시관에 올라가는 문제 수정 
- 알람클릭후 올해네컷 클릭하면 알람이 다시 나타나지않는문제 해결
- 알람 로그인 조건에따라 실행 적용
- 헤더사라지는 문제 해결
- 업로드후 라우팅 적용
- 파일사이즈 10메가로 변경
- 작품 제목, 내용 길이변경
>  🚑FIX: 버그 수정

- client/src/Intro/components/AIntro/index.tsx
- client/src/Intro/components/AIntro/style.tsx
- client/src/Intro/components/BIntro/index.tsx
- client/src/Intro/components/BIntro/style.tsx
- client/src/Intro/components/CIntro/index.tsx
- client/src/Intro/components/CIntro/style.tsx
- client/src/Intro/components/DynamicExample/index.tsx
- client/src/Intro/components/DynamicExample/style.tsx
- client/src/Intro/components/KakaoBtn/style.tsx
- client/src/Intro/components/Letter/index.tsx
- client/src/Intro/components/Scroll/index.tsx
- client/src/Intro/components/Scroll/style.tsx
- client/src/UploadPicture/index.tsx
> ✨FEAT : 사이트 소개 페이지

- client/src/AlarmList/index.tsx
- client/src/UploadPicture/components/Upload.tsx
- client/src/UploadPicture/components/UploadImg.tsx
- client/src/shared/components/Header/hook/useReceiveAlarm.tsx
> 🚑FIX: 버그 수정

- server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/dto/ArtworkResponseDto.java
- server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/controller/ArtworkControllerTest.java
- server/oneyearfourcut/src/test/resources/db/testdata.sql
> [BE/#187] Artwork 응답 데이터 추가

- client/src/AlarmList/components/Alarm.tsx
- client/src/AlarmList/types.ts
- client/src/SinglePicture/SinglePicture.tsx
- client/src/UploadPicture/api.ts
- client/src/UploadPicture/components/UploadImg.tsx
- client/src/UploadPicture/index.tsx
- client/src/UploadPicture/types.ts
- client/src/shared/components/Modal/Profile.tsx
- client/src/shared/components/Modal/components/ModalContainer.ts
- client/src/shared/components/Modal/components/ProfileModify.tsx
- client/src/shared/libs/uploadHelper.ts
- client/src/store/store.ts
- client/src/store/types.ts
- 로그인버튼 추가
- 알람 라우팅 수정
- cors에러로 인한 로직변경
> [FE] 업로드 페이지 로직변경
